# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f09e4ad3d85b0af10477b6d3b71f7bf712d1aafab72f037a4ada513f3208f5687315aaae03158f3067ac49a65b5c526bcdd6363376cf2f94cb530bde070e59

test:
  secret_key_base: 62f547e1dbdd04d5ba55bb2869a0c42940332e05a0c14333505d403eb2ffe9b97773bf09b88aa8e3b416cddcecd5010f0af5afbbe901dfbc311ab82a6924a696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
